import React, { useState } from 'react';
import './index.css';

const FAQ = () => {
  // State to track which FAQ is open
  const [openIndex, setOpenIndex] = useState(null);

  const faqs = [
    {
      question: 'How does Abun AI content writer work?',
      answer: 'Abun uses advanced GPT-4 based AI models trained on millions of high-quality articles. You simply enter your keyword, and our AI researches, outlines, writes, and optimizes a complete SEO-friendly article in 3-5 minutes. You can then edit, add images, and publish directly to your website.'
    },
    {
      question: 'Is the content unique and plagiarism-free?',
      answer: 'Yes! Every article generated by Abun is 100% unique and original. Our AI creates content from scratch based on your keyword and doesn\'t copy from existing sources. We also run plagiarism checks on all content before delivery.'
    },
    {
      question: 'How long does it take to rank on Google?',
      answer: 'Based on our user data, most websites start seeing ranking improvements within 30-60 days of consistently publishing Abun-generated content. However, ranking time depends on factors like domain authority, competition, backlinks, and niche.'
    },
    {
      question: 'Can I integrate Abun with my existing website?',
      answer: 'Absolutely! Abun integrates seamlessly with WordPress, Webflow, Wix, Shopify, and more. We also provide API access for custom integrations. You can auto-publish articles or export them as HTML/Markdown files.'
    },
    {
      question: 'What if I don\'t like the AI-generated content?',
      answer: 'You have full control! You can regenerate any section, edit the content manually, adjust the tone, add your own examples, and customize everything before publishing. Our built-in editor makes editing super easy.'
    },
    {
      question: 'Do you offer refunds?',
      answer: 'Yes, we offer a 30-day money-back guarantee. If you\'re not satisfied with Abun for any reason within the first 30 days, just contact our support team and we\'ll process a full refund - no questions asked.'
    }
  ];

  // Toggle FAQ open/close
  const toggleFAQ = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="faq-section">
      <div className="container">
        <div className="faq-header">
          <h2 className="section-title">
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
          <p className="section-subtitle">
            Got questions? We've got answers. Can't find what you're looking for? Contact our support team.
          </p>
        </div>

        <div className="faq-container">
          {faqs.map((faq, index) => (
            <div
              key={index}
              className={`faq-item ${openIndex === index ? 'open' : ''}`}
            >
              <button
                className="faq-question"
                onClick={() => toggleFAQ(index)}
              >
                <span>{faq.question}</span>
                <span className="faq-icon">
                  {openIndex === index ? '−' : '+'}
                </span>
              </button>
              <div className="faq-answer">
                <p>{faq.answer}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FAQ;
